seed: 0
dataset: "power"
batch_size: 10000
test_batch_size: 50000
n_knobs: 100
n_epochs: 400
hidden_size: 256
n_layers: 3
tag: "adacat"
fixed_x: False
residual: False
fourier_k: 0
smooth_coeff: 0.0001
weight_decay: 0.0001
ema_decay: 0.0
lr: 0.0003
scheduler_step_size: 100
scheduler_gamma: 0.5
